name: Deploy Lambda Layers

on:
  push: 
    branches:
      - master
  pull_request:
    branches:
      - master
    workflow_dispatch:

jobs:
  create-zip:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Python Library and Zip
        run: |
          cd src
          mkdir -p app/
          pip3 install -r requirements.txt -t app/
          cp . -r app/
          zip -r package.zip lambda_layers/

      - name: Upload Library Zip
        uses: actions/upload-artifact@v3
        with:
          name: layers-zip
          path: package.zip
